use Mix.Config

# Configure your database
config :team_heda, TeamHeda.Repo,
  username: "postgres",
  password: "password",
  database: "team_heda_dev",
  port: "5434",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :team_heda, TeamHedaWeb.Endpoint,
   http: [port: 4000],
   https: [
     port: 4001,
     cipher_suite: :strong,
     certfile: "priv/cert/selfsigned.pem",
     keyfile: "priv/cert/selfsigned_key.pem"
   ],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  live_view: [signing_salt: "VD4MRYE8EVXH1O8P5AsTC1cO2oeAqRO8"],
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]


config :oauth2, debug: false

config :team_heda, TeamHeda.ExternalService.Maniaplanet,
  redirect_uri: "http://localhost:4000/auth/maniaplanet/callback",
  authorize_url: "https://prod.live.maniaplanet.com/login/oauth2/authorize",
  token_url: "https://prod.live.maniaplanet.com/login/oauth2/access_token",
  site: "https://maniaplanet.com",
  response_type: "code"

  config :team_heda, TeamHeda.ExternalService.Discord,
    redirect_uri: "http://localhost:4000/auth/discord/callback",
    authorize_url: "https://discordapp.com/api/oauth2/authorize",
    token_url: "https://discordapp.com/api/oauth2/token",
    site: "https://discordapp.com",
    response_type: "code"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :team_heda, TeamHedaWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/team_heda_web/{live,views}/.*(ex)$",
      ~r"lib/team_heda_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime




import_config "dev.secret.exs"
